### ISSUE TITLE
[TODO] 프로젝트 목표

### ISSUE THREAD

**Issue by jseop-lim** [jseop-lim/anam-earth-be-fastapi#22]
## 주요 목표

- FastAPI + SQLArchemy 연습하기
- 클린 아키텍처 실습하기, DDD 일부 적용하기

## 부가 목표

- Git 부가기능 활용하기
  - [X] .gitmessage
  - [X] git-hook: pre-commit, commit-msg
  - [ ] git subtree / git submodule

- 파이썬 정적 도구 활용하기
  - [X] isort
  - [X] flake8
  - [X] black formatter
  - [X] 타입 검사기 mypy

- 파이썬 관련 도구 활용하기
  - [X] poetry 실사용 해보기
  - [ ] pytest coverage

- 프로그래밍 기타
  - [x] 의존성 주입 프레임워크 도입하기
  - [ ] _TDD 적용해보기_
  - [ ] API Versoning

- 인프라 신기술 연습
  - [ ] Docker
  - [ ] Amazon ECS
  - [ ] Amazon VPC
  - [ ] Amazon Code Deploy
  - [ ] terraform
  - [ ] Amazon S3 프론트 배포
  - [ ] 로그 쌓고 분석
  - [ ] Amazon CloudWatch 연동
